#define VLC_TS_INVALID (0)
#define VLC_TS_0 (1)

#define CLOCK_FREQ INT64_C(1000000)

#define INTF_IDLE_SLEEP (CLOCK_FREQ / 20)

#define INPUT_IDLE_SLEEP (CLOCK_FREQ / 10)

#define DEFAULT_PTS_DELAY (3 * CLOCK_FREQ / 10)

#define SPU_MAX_PREPARE_TIME (CLOCK_FREQ / 2)

#define VOUT_ASPECT_FACTOR 432000

#define VOUT_MAX_WIDTH 4096

#define VOUT_MAX_PLANES 5

#define VOUT_OUTMEM_SLEEP (CLOCK_FREQ / 50)

#define VOUT_TITLE "VLC"

#define MAX_DUMPSTRUCTURE_DEPTH 100
